# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
# Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
    exclude: ^(img/extern/IDR_ILD_quadrant_new_lstar.pdf|img/extern/pr_ilc_cavity_resized.png)
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: check-xml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: sort-simple-yaml
  - id: file-contents-sorter
  - id: trailing-whitespace
    exclude: ^doc/_static/.*.svg

# Python linter (Flake8)
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8

# Python formatting
- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
  - id: black

# pyupgrade
- repo: https://github.com/asottile/pyupgrade
  rev: v2.23.0
  hooks:
  - id: pyupgrade
    args: ["--py37-plus"]

# Sorted python imports
- repo: https://github.com/PyCQA/isort
  rev: 5.9.2
  hooks:
    - id: isort
      args: ["--profile", "black"]

# Typing
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy
      exclude: ^docs/
