name: make-all

on:
  pull_request:
  push:
    branches:
      - master
      - eps
      - fcc_france_workshop

jobs:
  make-all:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Setup Python Version
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: python -m pip install --upgrade pip wheel
    - run: python -m pip install -r code/requirements.txt

    - name: Setup pdflatex
      run: sudo apt-get install latexmk texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-lang-french
    - name: Execute the Makefile
      run: |
        make all

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Commit to orphan branch
      run: |
        echo $(ls -lah)
        echo $(ls -lah build)
        git add -f build/*.pdf
        git add -f img/code/*
        git checkout --orphan gh-action-result/make-all-${GITHUB_REF##*/}
        git -c user.name='GitHub Action' -c user.email='action@github.com' commit -m "Build current code/paper version"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-action-result/make-all-${{ steps.extract_branch.outputs.branch }}
        force: true
